spring:
  datasource:
    url: jdbc:h2:./currencies
    username: user
    password: user

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop

period:
 days: 20
 cron: "0 0 0 1/1 * *"